version: '3.8'

services:
  vietqr-grpc:
    image: ghcr.io/williamsmiths/vietqr-1:latest
    container_name: vietqr-1:latest
    ports:
      - "9090:9090"  # gRPC port
    environment:
      - GRPC_PORT=9090
    restart: unless-stopped
    networks:
      - tiemco-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  tiemco-network:
    name: tiemco-network
    external: false 
